=== osmhpi/interlocking/geographical_interlocking/simulator/configuration.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Entities",
  "type": "object",
  "properties": {
    "Ise": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "is_start_of_route_admission_check": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Indicates whether this ISE is the start of a route admission checking.",
            "minItems": 0
          },
          "is_end_of_route_admission_check": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Indicates whether this ISE is the end of a route admission checking.",
            "minItems": 0
          },
          "link_a_left": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Link with left side connected to port A.",
            "minItems": 0
          },
          "link_a_right": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Link with right side connected to port A.",
            "minItems": 0
          },
          "link_b_left": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Link with left side connected to port B.",
            "minItems": 0
          },
          "link_b_right": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Link with right side connected to port B.",
            "minItems": 0
          },
          "link_c_left": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Link with left side connected to port C.",
            "minItems": 0
          },
          "link_c_right": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Link with right side connected to port C.",
            "minItems": 0
          },
          "point": {
            "type": "string",
            "description": "Point that this ISE refers to."
          },
          "zone": {
            "type": "string",
            "description": "Zone that this ISE refers to."
          },
          "transits": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Transits that this ISE refers to.",
            "minItems": 0
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Link": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ise_left_port_a": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Left ISE of the link, connected at port A.",
            "minItems": 0
          },
          "ise_left_port_b": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Left ISE of the link, connected at port B.",
            "minItems": 0
          },
          "ise_left_port_c": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Left ISE of the link, connected at port C.",
            "minItems": 0
          },
          "ise_right_port_a": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Right ISE of the link, connected at port A.",
            "minItems": 0
          },
          "ise_right_port_b": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Right ISE of the link, connected at port B.",
            "minItems": 0
          },
          "ise_right_port_c": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Right ISE of the link, connected at port C.",
            "minItems": 0
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Point": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ise": {
            "type": "string",
            "description": "ISE that this point belongs to."
          },
          "all_points": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "All points in the interlocking.",
            "minItems": 1
          },
          "locked_left_by_transits": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Transits that require the point to be set to left.",
            "minItems": 0
          },
          "locked_right_by_transits": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Transits that require the point to be set to right.",
            "minItems": 0
          },
          "locked_left_by_zones": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Zones that require the point to be set to left.",
            "minItems": 0
          },
          "locked_right_by_zones": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Zones that require the point to be set to right.",
            "minItems": 0
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "ise",
          "all_points",
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Route": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "all_routes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "All routes that are part of this station.",
            "minItems": 0
          },
          "start_ise_left": {
            "type": "string",
            "description": "The start ISE of the route."
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Signal": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "routes_starting_here": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Routes that start at this signal.",
            "minItems": 0
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Station": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "all_routes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "All routes that are part of this station.",
            "minItems": 0
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Transit": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ise": {
            "type": "string",
            "description": "ISE that this transit belongs to."
          },
          "underlying_zone": {
            "type": "string",
            "description": "The underlying zone that forms this transit."
          },
          "upstream_transits": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Transits that lead to this transit.",
            "minItems": 0
          },
          "requires_point_left": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The point that is required to be in the left position.",
            "minItems": 0
          },
          "requires_point_right": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The point that is required to be in the right position.",
            "minItems": 0
          },
          "upstream_link_left": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The link that leads to this transit, connected to its left end.",
            "minItems": 0
          },
          "upstream_link_right": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The link that leads to this transit, connected to its right end.",
            "minItems": 0
          },
          "downstream_link_left": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The link that leads from this transit, connected to its left end.",
            "minItems": 0
          },
          "downstream_link_right": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The link that leads from this transit, connected to its right end.",
            "minItems": 0
          },
          "transit_in_opposite_direction": {
            "type": "string",
            "description": "The transit that is in the opposite direction."
          },
          "trigger_zone": {
            "type": "string",
            "description": "Trigger zone that is used to release a route that starts from this transit."
          },
          "trigger_zone_opposite_transits": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Transits of the route release trigger zone in opposite direction of the route.",
            "minItems": 0
          },
          "approach_zone": {
            "type": "string",
            "description": "Approach zone of the route that starts from this transit."
          },
          "time_delay_etcs_approach_locking": {
            "type": "integer",
            "description": "Time delay for ETCS approach locking."
          },
          "time_delay_unsupervised_train_approach_locking": {
            "type": "integer",
            "description": "Time delay for unsupervised train approach locking."
          },
          "signal": {
            "type": "string",
            "description": "Signal that directly protects this transit."
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "ise",
          "underlying_zone",
          "transit_in_opposite_direction",
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Zone": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ise": {
            "type": "string",
            "description": "ISE that this zone belongs to."
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "ise",
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    }
  },
  "additionalProperties": false
}

=== osmhpi/interlocking/geographical_interlocking/specific_application/configuration.json
{
  "Signal": [
    {
      "name": "A",
      "routes_starting_here": ["G11+"]
    },
    {
      "name": "N1",
      "routes_starting_here": []
    },
    {
      "name": "N2",
      "routes_starting_here": []
    }
  ],
  "Ise": [
    {
      "name": "A",
      "is_start_of_route_admission_check": ["A.N1", "A.N2"],
      "is_end_of_route_admission_check": [],
      "link_b_left": ["link_1"],
      "transits": ["G11+", "G11-"]
    },
    {
      "name": "W1",
      "is_start_of_route_admission_check": [],
      "is_end_of_route_admission_check": [],
      "link_a_right": ["link_1"],
      "link_b_left": ["link_2"],
      "link_c_left": ["link_3"],
      "point": "W1",
      "transits": ["W1_R+", "W1_R-", "W1_L+", "W1_L-"]
    },
    {
      "name": "W2",
      "is_start_of_route_admission_check": [],
      "is_end_of_route_admission_check": [],
      "link_a_left": ["link_4"],
      "link_c_right": ["link_3"],
      "point": "W2",
      "transits": ["W2_R+", "W2_R-", "W2_L+", "W2_L-"]
    },
    {
      "name": "N1",
      "is_start_of_route_admission_check": [],
      "is_end_of_route_admission_check": ["A.N1"],
      "link_a_right": ["link_2"],
      "transits": ["G12+", "G12-"]
    },
    {
      "name": "N2",
      "is_start_of_route_admission_check": [],
      "is_end_of_route_admission_check": ["A.N2"],
      "link_a_right": ["link_4"],
      "transits": ["G21+", "G21-"]
    }
  ],
  "Link": [
    {
      "name": "link_1",
      "ise_left_port_b": ["A"],
      "ise_right_port_a": ["W1"]
    },
    {
      "name": "link_2",
      "ise_left_port_b": ["W1"],
      "ise_right_port_a": ["N1"]
    },
    {
      "name": "link_3",
      "ise_left_port_c": ["W1"],
      "ise_right_port_c": ["W2"]
    },
    {
      "name": "link_4",
      "ise_left_port_a": ["W2"],
      "ise_right_port_a": ["N2"]
    }
  ],
  "Route": [
    {
      "name": "A.N1",
      "start_ise_left": "A",
      "all_routes": [
        "A.N1"
      ]
    },
    {
      "name": "A.N2",
      "start_ise_left": "A",
      "all_routes": [
        "A.N2"
      ]
    }
  ],
  "Point": [
    {
      "name": "W1",
      "ise": "W1",
      "locked_left_by_transits": ["W1_L+", "W1_L-"],
      "locked_right_by_transits": ["W1_R+", "W1_R-"],
      "all_points": [
        "W1",
        "W2"
      ]
    },
    {
      "name": "W2",
      "ise": "W2",
      "locked_left_by_transits": ["W2_L+", "W2_L-"],
      "locked_right_by_transits": ["W2_R+", "W2_R-"],
      "all_points": [
        "W1",
        "W2"
      ]
    }
  ],
  "Station": [
    {
      "name": "Example",
      "all_routes": [
        "A.N1",
        "A.N2"
      ]
    }
  ],
  "Transit": [
    {
      "name": "G11+",
      "ise": "A",
      "underlying_zone": "G11",
      "upstream_transits": [],
      "downstream_link_left": ["link_1"],
      "transit_in_opposite_direction": "G11-",
      "trigger_zone": "W1",
      "trigger_zone_opposite_transits": ["W1_R-", "W1_L-"],
      "approach_zone": "G11",
      "signal": "A",
      "time_delay_etcs_approach_locking": 1000,
      "time_delay_unsupervised_train_approach_locking": 1000
    },
    {
      "name": "G11-",
      "ise": "A",
      "underlying_zone": "G11",
      "upstream_transits": ["W1_R-", "W1_L-"],
      "upstream_link_left": ["link_1"],
      "transit_in_opposite_direction": "G11+"
    },
    {
      "name": "W1_R+",
      "ise": "W1",
      "underlying_zone": "W1",
      "upstream_transits": [],
      "requires_point_right": ["W1"],
      "upstream_link_right": ["link_1"],
      "downstream_link_left": ["link_2"],
      "transit_in_opposite_direction": "W1_R-"
    },
    {
      "name": "W1_R-",
      "ise": "W1",
      "underlying_zone": "W1",
      "upstream_transits": ["G12-"],
      "requires_point_right": ["W1"],
      "upstream_link_left": ["link_2"],
      "downstream_link_right": ["link_1"],
      "transit_in_opposite_direction": "W1_R+"
    },
    {
      "name": "W1_L+",
      "ise": "W1",
      "underlying_zone": "W1",
      "upstream_transits": [],
      "requires_point_left": ["W1"],
      "upstream_link_right": ["link_1"],
      "downstream_link_left": ["link_3"],
      "transit_in_opposite_direction": "W1_L-"
    },
    {
      "name": "W1_L-",
      "ise": "W1",
      "underlying_zone": "W1",
      "upstream_transits": ["W2_L+"],
      "requires_point_left": ["W1"],
      "upstream_link_left": ["link_3"],
      "downstream_link_right": ["link_1"],
      "transit_in_opposite_direction": "W1_L+"
    },
    {
      "name": "W2_R+",
      "ise": "W2",
      "underlying_zone": "W2",
      "upstream_transits": ["G21-"],
      "requires_point_right": ["W2"],
      "upstream_link_left": ["link_4"],
      "transit_in_opposite_direction": "W2_R-"
    },
    {
      "name": "W2_R-",
      "ise": "W2",
      "underlying_zone": "W2",
      "upstream_transits": [],
      "requires_point_right": ["W2"],
      "downstream_link_left": ["link_4"],
      "transit_in_opposite_direction": "W2_R+"
    },
    {
      "name": "W2_L+",
      "ise": "W2",
      "underlying_zone": "W2",
      "upstream_transits": ["G21-"],
      "requires_point_left": ["W2"],
      "upstream_link_left": ["link_4"],
      "downstream_link_right": ["link_3"],
      "transit_in_opposite_direction": "W2_L-"
    },
    {
      "name": "W2_L-",
      "ise": "W2",
      "underlying_zone": "W2",
      "upstream_transits": ["W1_L+"],
      "requires_point_left": ["W2"],
      "upstream_link_right": ["link_3"],
      "downstream_link_left": ["link_4"],
      "transit_in_opposite_direction": "W2_L+"
    },
    {
      "name": "G12+",
      "ise": "N1",
      "underlying_zone": "G12",
      "upstream_transits": ["W1_R+"],
      "upstream_link_right": ["link_2"],
      "transit_in_opposite_direction": "G12-"
    },
    {
      "name": "G12-",
      "ise": "N1",
      "underlying_zone": "G12",
      "upstream_transits": [],
      "downstream_link_right": ["link_2"],
      "transit_in_opposite_direction": "G12+"
    },
    {
      "name": "G21+",
      "ise": "N2",
      "underlying_zone": "G21",
      "upstream_transits": ["W2_R-", "W2_L-"],
      "upstream_link_right": ["link_3"],
      "transit_in_opposite_direction": "G21-"
    },
    {
      "name": "G21-",
      "ise": "N2",
      "upstream_transits": [],
      "underlying_zone": "G21",
      "downstream_link_right": ["link_3"],
      "transit_in_opposite_direction": "G21+"
    }
  ],
  "Zone": [
    {
      "name": "G11",
      "ise": "A"
    },
    {
      "name": "W1",
      "ise": "W1"
    },
    {
      "name": "W2",
      "ise": "W2"
    },
    {
      "name": "G12",
      "ise": "N1"
    },
    {
      "name": "G21",
      "ise": "N2"
    }
  ]
}
