=== osmhpi/interlocking/locking_table_interlocking/simulator/configuration.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Entities",
  "type": "object",
  "properties": {
    "Point": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "requested_left_by_routes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Routes that request the point to be set to left.",
            "minItems": 0
          },
          "requested_right_by_routes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Routes that request the point to be set to right.",
            "minItems": 0
          },
          "locked_left_by_transits": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Transits that require the point to be set to left.",
            "minItems": 0
          },
          "locked_right_by_transits": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Transits that require the point to be set to right.",
            "minItems": 0
          },
          "locked_left_by_zones": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Zones that require the point to be set to left.",
            "minItems": 0
          },
          "locked_right_by_zones": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Zones that require the point to be set to right.",
            "minItems": 0
          },
          "all_points": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "All points in the interlocking.",
            "minItems": 1
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "all_points",
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Route": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "request_points_right": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Points that are requested to be set to right.",
            "minItems": 0
          },
          "request_points_left": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Points that are requested to be set to left.",
            "minItems": 0
          },
          "request_points_controlled_right": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Points that must be controlled in right end position.",
            "minItems": 0
          },
          "request_points_controlled_left": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Points that must be controlled in left end position.",
            "minItems": 0
          },
          "transits_in_opposite_route_direction": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Transits that are in opposite direction of the route.",
            "minItems": 0
          },
          "trigger_zone": {
            "type": "string",
            "description": "Trigger zone that is used to release the route."
          },
          "trigger_zone_opposite_transit": {
            "type": "string",
            "description": "Transit of the trigger zone in opposite direction of the route."
          },
          "start_signal": {
            "type": "string",
            "description": "Start signal of the route."
          },
          "approach_zone": {
            "type": "string",
            "description": "Approach zone of the route."
          },
          "time_delay_etcs_approach_locking": {
            "type": "integer",
            "description": "Time delay for ETCS approach locking."
          },
          "time_delay_unsupervised_train_approach_locking": {
            "type": "integer",
            "description": "Time delay for unsupervised train approach locking."
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "trigger_zone",
          "trigger_zone_opposite_transit",
          "start_signal",
          "approach_zone",
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Signal": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "routes_starting_here": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Routes that start at this signal.",
            "minItems": 0
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Transit": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "activating_routes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Routes that activate this transit.",
            "minItems": 0
          },
          "underlying_zone": {
            "type": "string",
            "description": "The underlying zone that forms this transit."
          },
          "upstream_transits": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Transits that lead to this transit.",
            "minItems": 0
          },
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "underlying_zone",
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    },
    "Zone": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the entity instance.",
            "minItems": 1,
            "maxItems": 1
          }
        },
        "required": [
          "name"
        ],
        "additionalProperties": false
      },
      "minItems": 0
    }
  },
  "additionalProperties": false
}

=== osmhpi/interlocking/locking_table_interlocking/specific_application/configuration.json
{
  "Route": [
    {
      "name": "A.N1",
      "request_points_right": ["W1"],
      "request_points_left": [],
      "request_points_controlled_right": ["W1"],
      "request_points_controlled_left": [],
      "transits_in_opposite_route_direction": ["W1_R-", "G12-"],
      "trigger_zone": "W1",
      "trigger_zone_opposite_transit": "W1_R-",
      "start_signal": "A",
      "approach_zone": "G11",
      "time_delay_etcs_approach_locking": 1000,
      "time_delay_unsupervised_train_approach_locking": 1000
    },
    {
      "name": "A.N2",
      "request_points_right": [],
      "request_points_left": ["W1", "W2"],
      "request_points_controlled_right": [],
      "request_points_controlled_left": ["W1", "W2"],
      "transits_in_opposite_route_direction": ["W1_L-", "G21-"],
      "trigger_zone": "W1",
      "trigger_zone_opposite_transit": "W1_L-",
      "start_signal": "A",
      "approach_zone": "G11",
      "time_delay_etcs_approach_locking": 1000,
      "time_delay_unsupervised_train_approach_locking": 1000
    }
  ],
  "Point": [
    {
      "name": "W1",
      "requested_left_by_routes": ["A.N2"],
      "requested_right_by_routes": ["A.N1"],
      "all_points": ["W1", "W2"]
    },
    {
      "name": "W2",
      "requested_left_by_routes": ["A.N2"],
      "requested_right_by_routes": [],
      "all_points": ["W1", "W2"]
    }
  ],
  "Zone": [
    {
      "name": "G11"
    },
    {
      "name": "W1"
    },
    {
      "name": "W2"
    },
    {
      "name": "G12"
    },
    {
      "name": "G21"
    }
  ],
  "Transit": [
    {
      "name": "G11+",
      "underlying_zone": "G11",
      "upstream_transits": [],
      "activating_routes": ["A.N1", "A.N2"]
    },
    {
      "name": "G11-",
      "underlying_zone": "G11",
      "upstream_transits": ["W1_R-", "W1_L-"],
      "activating_routes": []
    },
    {
      "name": "W1_R+",
      "underlying_zone": "W1",
      "upstream_transits": [],
      "activating_routes": ["A.N1"]
    },
    {
      "name": "W1_R-",
      "underlying_zone": "W1",
      "upstream_transits": ["G12-"],
      "activating_routes": []
    },
    {
      "name": "W1_L+",
      "underlying_zone": "W1",
      "upstream_transits": [],
      "activating_routes": ["A.N2"]
    },
    {
      "name": "W1_L-",
      "underlying_zone": "W1",
      "upstream_transits": ["W2_L+"],
      "activating_routes": []
    },
    {
      "name": "W2_R+",
      "underlying_zone": "W2",
      "upstream_transits": ["G21-"],
      "activating_routes": []
    },
    {
      "name": "W2_R-",
      "underlying_zone": "W2",
      "upstream_transits": [],
      "activating_routes": []
    },
    {
      "name": "W2_L+",
      "underlying_zone": "W2",
      "upstream_transits": ["G21-"],
      "activating_routes": []
    },
    {
      "name": "W2_L-",
      "underlying_zone": "W2",
      "upstream_transits": ["W1_L+"],
      "activating_routes": ["A.N2"]
    },
    {
      "name": "G12+",
      "underlying_zone": "G12",
      "upstream_transits": ["W1_R+"],
      "activating_routes": ["A.N1"]
    },
    {
      "name": "G12-",
      "underlying_zone": "G12",
      "upstream_transits": [],
      "activating_routes": []
    },
    {
      "name": "G21+",
      "underlying_zone": "G21",
      "upstream_transits": ["W2_R-", "W2_L-"],
      "activating_routes": ["A.N2"]
    },
    {
      "name": "G21-",
      "underlying_zone": "G21",
      "upstream_transits": [],
      "activating_routes": []
    }
  ],
  "Signal": [
    {
      "name": "A",
      "routes_starting_here": ["A.N1", "A.N2"]
    },
    {
      "name": "N1",
      "routes_starting_here": []
    },
    {
      "name": "N2",
      "routes_starting_here": []
    }
  ]
}
